import { ArrowRightOutlined, FileAddOutlined, FileTextOutlined, PlusOutlined, ReloadOutlined, SearchOutlined, UserOutlined } from '@ant-design/icons';
import { Alert, Button, Card, Col, Empty, Form, Input, Modal, Pagination, Row, Skeleton, Space, Tag, Typography, message } from 'antd';
import { useCallback, useEffect, useState } from 'react';
import { Link, useLocation } from 'react-router-dom';
import apiClient, { apiErrorMessage } from '../api/apiClient';
import { useI18n } from '../i18n';
const getUser = () => { try { return JSON.parse(sessionStorage.getItem('assessment_user')) || null; } catch { return null; } };
export default function AssessmentList() {
  const { t } = useI18n(); const locale = useLocation().pathname.split('/')[1] || 'vi'; const user = getUser(); const [items, setItems] = useState([]); const [total, setTotal] = useState(0); const [page, setPage] = useState(1); const [search, setSearch] = useState(''); const [query, setQuery] = useState(''); const [state, setState] = useState('loading'); const [error, setError] = useState(''); const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false); const [form] = Form.useForm();
  const load = useCallback(async () => { setState('loading'); try { const response = await apiClient.get('/assessment/v1/assessments', { params: { page, per_page: 9, search: query } }); setItems(response.data); setTotal(Number(response.headers['x-wp-total'] || 0)); setState('ready'); } catch (err) { setError(apiErrorMessage(err, t)); setState('error'); } }, [page, query, t]);
  useEffect(() => { load(); }, [load]);
  const submitSearch = () => { setPage(1); setQuery(search.trim()); };
  const resetSearch = () => { const hasActiveSearch = Boolean(search || query || page !== 1); setSearch(''); setQuery(''); setPage(1); if (!hasActiveSearch) load(); };
  const create = async (values) => { setSaving(true); try { await apiClient.post('/assessment/v1/assessments', { ...values, status: 'publish' }); setOpen(false); form.resetFields(); message.success(t('createSuccess')); setPage(1); load(); } catch (err) { message.error(apiErrorMessage(err, t)); } finally { setSaving(false); } };
  return <section className="page-wrap"><div className="hero-panel"><div><Tag>{t('learningHub')}</Tag><Typography.Title>{t('discover')}</Typography.Title><Typography.Paragraph>{t('discoverHint')}</Typography.Paragraph><Tag icon={<UserOutlined />}>{user?.display_name || t('publicCatalog')}</Tag></div><FileTextOutlined className="hero-icon" /></div><div className="section-heading"><div><Typography.Title level={2}>{t('assessments')}</Typography.Title><Typography.Text type="secondary">{t('assessmentsHint')}</Typography.Text></div><Space>{user?.permissions?.actions?.assessment?.create && <Button type="primary" icon={<PlusOutlined />} onClick={() => setOpen(true)}>{t('createAssessment')}</Button>}<Tag className="count-tag">{total} {t('published')}</Tag></Space></div><Space.Compact className="list-search"><Input.Search value={search} onChange={(event) => setSearch(event.target.value)} onSearch={submitSearch} placeholder={t('searchAssessments')} enterButton={<SearchOutlined />} allowClear /><Button icon={<ReloadOutlined />} onClick={resetSearch}>{t('resetSearch')}</Button></Space.Compact>{state === 'loading' && <Skeleton active />}{state === 'error' && <Alert type="error" message={error} action={<Button onClick={load}>{t('retry')}</Button>} />}{state === 'ready' && !items.length && <Empty description={t('noAssessments')} />}{state === 'ready' && <Row gutter={[20, 20]}>{items.map((item) => <Col xs={24} md={12} lg={8} key={item.id}><Link className="assessment-card-link" to={`/${locale}/assessment/${item.id}`} aria-label={`${t('openAssessment')}: ${item.title}`}><Card className="assessment-card" hoverable><FileTextOutlined className="assessment-icon" /><Typography.Title level={4}>{item.title}</Typography.Title><Typography.Paragraph ellipsis={{ rows: 3 }}>{item.description || t('noDescription')}</Typography.Paragraph><span className="card-link">{t('openAssessment')} <ArrowRightOutlined /></span></Card></Link></Col>)}</Row>}{total > 9 && <Pagination className="list-pagination" current={page} pageSize={9} total={total} showSizeChanger={false} onChange={setPage} />}<Modal title={<Space><FileAddOutlined />{t('createAssessmentNew')}</Space>} open={open} onCancel={() => setOpen(false)} footer={null}><Form form={form} layout="vertical" onFinish={create}><Form.Item name="title" label={t('assessmentTitle')} rules={[{ required: true, message: t('titleRequired') }]}><Input placeholder={t('titlePlaceholder')} /></Form.Item><Form.Item name="description" label={t('description')}><Input.TextArea rows={4} placeholder={t('descriptionPlaceholder')} /></Form.Item><Button type="primary" htmlType="submit" loading={saving} block>{t('createAssessment')}</Button></Form></Modal></section>;
}
